### ISSUE TITLE
Why hard code the font family?

### ISSUE THREAD

**Issue by kentliau** [coopermaruyama/atom-vivid-syntax#2]

**Comment by czxtm** [comment]
Hey, thanks for asking!

It's been a while since I wrote that, but since the font is included with the package, you can assume it's pretty opinionated towards it. The other reason I like this font is that it has tons of font-weights.

Source Code Pro is not a standard font, which is preferred for this package, so it's included with the package. When you type a font name into the atom settings, that font will only work if it's globally installed on your machine - it doesn't let you choose the path to the font. Hard-coding it in allows us to set the path. The good thing is that even with it hard-coded in, anything you put in atom settings should override it.
